### ISSUE TITLE
User stats

### ISSUE THREAD

**Issue by mariuscoto** [maria/cub#12]
## Need

We need to have some user stats on his/her profile page.
## Deliverables

Add the following attributes to `/api/v1/myaccount/` response:
- watchers - total number of watchers on all public repos (owned or collaborative ones)
- stars - total number of stars on all public repos (owned or collaborative ones)
- pulls - total number of pull requests on all public repos (owned or collaborative ones)

**Comment by maria** [comment]
You have:

```
watchers_count
stargazers_count
forks_count
pulls_count
```
