### ISSUE TITLE
Allow unauthenticated requests

### ISSUE THREAD

**Issue by mariuscoto** [maria/cub#15]
## Need

When a new (unauthenticated) user accesses the site, he should see some (not all) info about other users.
## Deliverables

Provide new endpoints:
- for profile: show name, username, avatar
- for repos: show list of repos, but no score

**Comment by maria** [comment]
Done. Now you have `/api/public` for public stuff: `/api/public/contact`, `/api/public/account` and `/api/public/repository/` and `/api/v1/myaccount` is now `/api/v1/account`
