### ISSUE TITLE
Another user's profile

### ISSUE THREAD

**Issue by mariuscoto** [maria/cub#8]
## Need

Add ability to view another user's profile.
## Deliverables

GET `/api/v1/account/USER/?format=json`
where USER is a GitHub username
## Notes

We must include:
- 404 page for users that have never logged in

**Comment by maria** [comment]
Done - You can use `http://192.168.3.3:8000/api/v1/account/?username=maria` for filtering, and you can see all users.  To access the logged in user information use  `http://192.168.3.3:8000/api/v1/myaccount/`
