### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by mariuscoto** [maria/cub#9]
## Need

Have a method to receive feedback from users.
## Deliverables

Have a contact form in the Contact page.
Enable an `POST /api/v1/contact` endpoint, which send an email to us, containing the feedback from the contact form.

**Comment by maria** [comment]
Endpoint done, sending the email done. I need to make a nice email template.
And you should do the form. :)

**Comment by maria** [comment]
Templates are done. You need to finish the form.
